using Coliseum.Application.Ports;

namespace Coliseum.Infrastructure.Redis.Adapters;

/// <summary>
/// ULID-style identifiers: a UUID version 7 (48-bit millisecond timestamp followed by random bits, generated by
/// the runtime) encoded as 26 Crockford base32 characters. Time-sortable, URL-safe, within the domain's id rule,
/// and free of any extra package.
/// </summary>
public sealed class UlidIdGenerator : IIdGenerator
{
    private const string Alphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

    public string NewId()
    {
        Span<byte> bytes = stackalloc byte[16];
        Guid.CreateVersion7().TryWriteBytes(bytes, bigEndian: true, out _);
        return Encode(bytes);
    }

    /// <summary>128 bits -> 26 symbols of 5 bits (the first symbol carries the 3 leading bits), as in the ULID spec.</summary>
    internal static string Encode(ReadOnlySpan<byte> bytes)
    {
        Span<char> chars = stackalloc char[26];
        int bitBuffer = 0;
        int bitCount = 0;
        int position = 25;

        // Walk from the least significant byte so each 5-bit group lands at the right end of the string.
        for (int i = 15; i >= 0; i--)
        {
            bitBuffer |= bytes[i] << bitCount;
            bitCount += 8;
            while (bitCount >= 5)
            {
                chars[position--] = Alphabet[bitBuffer & 0x1F];
                bitBuffer >>= 5;
                bitCount -= 5;
            }
        }

        chars[position] = Alphabet[bitBuffer & 0x1F];
        return new string(chars);
    }
}
