using Coliseum.Domain.Common;

namespace Coliseum.Domain.Players;

/// <summary>
/// Strongly-typed player identifier. A <c>string</c> parameter can silently receive a battle id or a name;
/// a <see cref="PlayerId"/> cannot. Values are ULIDs in production (time-sortable, URL-safe) but the domain
/// only enforces the character set and length, see <see cref="Identifier"/>.
/// </summary>
public readonly record struct PlayerId
{
    private PlayerId(string value) => Value = value;

    public string Value { get; }

    /// <summary>Validates external input (request bodies, route values). Returns a validation error on bad format.</summary>
    public static Result<PlayerId> Create(string? value) =>
        Identifier.IsValid(value)
            ? Result.Ok(new PlayerId(value))
            : Result.Fail<PlayerId>(DomainError.Validation("playerId", "player.id.invalid", "Player id must be 1-64 characters from [A-Za-z0-9_-]."));

    /// <summary>
    /// Wraps a value that is already known to be valid: ids generated by the system or read back from storage.
    /// Never use it for user input.
    /// </summary>
    public static PlayerId Unchecked(string value) => new(value);

    public override string ToString() => Value ?? string.Empty;
}
